
version: '3.8'
services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    depends_on:
      - mongo-seed
  mongo-seed:
    image: mongo:latest
    volumes:
      - ./dataset.json:/datasets/dataset.json
    command: mongoimport --host mongodb -d cocktails -c cocktails --type json --file /datasets/dataset.json --jsonArray
